const companies = {

  cristalia: {
    name: "CristÃ¡lia - IndÃºstria FarmacÃªutica",
    domain: "CRISTALIA.COM.BR",
    size: "900 GB",
    logo: "logo/CRISTALIA.jpg",
    description: `Fundado hÃ¡ 49 anos, o LaboratÃ³rio CristÃ¡lia Ã© um Complexo Industrial FarmacÃªutico, FarmoquÃ­mico, BiotecnolÃ³gico, de Pesquisa, Desenvolvimento e InovaÃ§Ã£o 100% brasileiro. Ã‰ pioneiro na realizaÃ§Ã£o da cadeia completa de um medicamento, desde a concepÃ§Ã£o da molÃ©cula atÃ© o produto final. O Grupo CristÃ¡lia possui 112 patentes, sendo recordista nacional, e em anestesia, Ã© lÃ­der de mercado na AmÃ©rica Latina. Produz 53% das matÃ©rias-primas dos seus medicamentos na planta FarmoquÃ­mica e estÃ¡ presente em mais de 95% dos hospitais brasileiros, sendo referÃªncia no Ã¢mbito internacional com exportaÃ§Ã£o de princÃ­pios ativos e produtos acabados para mais de 30 paÃ­ses. AlÃ©m disso, possui uma das primeiras plantas privadas de Biotecnologia do Brasil. O Grupo CristÃ¡lia conta com cerca de 5.600 colaboradores, considerando as empresas os laboratÃ³rios BioChimico, no Rio de Janeiro, e IMA, na Argentina. Sito Web http://www.cristalia.com.br Settori Industria farmaceutica Dimensioni dell'azienda 5001-10.000 dipendenti Sede principale Itapira, SÃƒO PAULO Tipo SocietÃ  privata non quotata Data di fondazione 1972`,
    data: [
      "biotec",
      "citostaticos",
      "colagenase_injetavel",
      "contab",
      "controladoria_obras",
      "DMF",
      "expedicao",
      "hospitalar",
      "licitacao",
      "MOC",
      "patentes",
      "relacoes_institucionais",
      "avaliacao_projetos_produtos_bc",
      "novos_projetos",
      "farmoquimica",
      "fiscal"
    ]
  },

  tegravendas: {
    name: "Tegra Vendas",
    domain: "TEGRAINCORPORADORA.COM.BR",
    size: "620 GB",
    logo: "logo/tegra.jpg",
    description: `We are a leading Company in the real estate development market, acting in the mid and high income residential segments in the metropolitan areas of SÃ£o Paulo, Rio de Janeiro and Campinas, and in the urban development segment through the TamborÃ© brand.

Throughout our history, we have undertaken projects that have made history and transformed regions, revealing a genuine concern for the quality of life in cities. We have 47 years of experience in the national market, and, since the beginning of our new phase, with the creation of the Tegra brand, the Company has over 1.8 million square meters built and under construction, over 15 thousand units delivered and over 30 awards received.

We are part of the Brookfield Corporation, a publicly traded Canadian group listed on the New York and Toronto stock exchanges under the symbol BN, and which has over USD 1 trillion of assets under management, operates in more than 30 countries and participates in the most diverse sectors of the economy, concentrating its investments in Brazil in the following segments: real estate, infrastructure, renewable energy, sustainable resources and private equity.`,
    data: [
    "contratos_venda_2021",
    "contratos_locacao",
    "clientes_pessoa_fisica",
    "clientes_pessoa_juridica",
    "cadastro_imoveis",
    "matriculas_imoveis",
    "escrituras_publicas",
    "plantas",
    "projetos_residenciais",
    "projetos_comerciais",
    "avaliacao_imobiliaria",
    "financiamento_bancario",
    "relacoes_bancarias",
    "comissoes_corretagem",
    "corretores_cadastro",
    "documentos_fiscais",
    "contabilidade",
    "fiscal",
    "juridico",
    "recursos_humanos",
    "folha_pagamento",
    "marketing_imobiliario",
    "campanhas_publicitarias",
    "leads_clientes",
    "CRM",
    "suporte_pos_venda",
    "inadimplencia",
    "acordos_judiciais",
    "due_diligence"
    ]
  },

  eisai: {
    name: "Eisai Co., Ltd",
    domain: "EISAI.COM",
    size: "1.5 TB",
    logo: "logo/eisai.png",
    description: `A Leading Global Research and Development-Based Pharmaceutical Company Headquartered in Japan
Established in 1941, Eisai is a pharmaceutical company operating globally in terms of R&D, manufacturing  and marketing, with a strong focus on prescription medicines.`,
    data: [
    "R&D_internal_2021",
    "ONCO_Trial",
    "clinical_trials_tokyo",
    "regulatory_JP_notes",
    "lab-notes",
    "rawdata",
    "BioDiv_ProjectA",
    "patient_safety_review",
    "PV_alerts_2021_Q1",
    "HR_master_2021",
    "salarystructure",
    "employeelist_full",
    "finance_FY23_draft",
    "budget_planning_2021_v1",
    "production_lineC_logs",
    "FactoryA_shift_report",
    "maintenance_Records_MainLab",
    "QC-checklists",
    "FORMULATION_v5",
    "API_synthesis_notes",
    "supplier_contracts_main",
    "procurement_Jan2020",
    "shipmentcargo2",
    "EXPORT_docs_2020_EU",
    "distribution_map_internal",
    "marketingcampaign",
    "promo_assets_2021",
    "meeting_minutes_ExecBd",
    "legal",
    "Vaccine_Dev_Project",
    "animal_study_logs",
    "toxicity_results_setC",
    "compound_library_index",
    "cell_line_inventory_2020",
    "DeviceCalibration_MainLab",
    "audit_prep_internal",
    "risk_assessment_2021",
    "Operational_Data_Room",
    "DATA_BACKUP_OLD_SERVER",
    "archive_2017_to_2019",
    "project_Hikari"
    ]
  },

  lightcon: {
    name: "LIGHT CONVERSION",
    domain: "LIGHTCON.COM",
    size: "1.3 TB",
    logo: "logo/lightcon.jpg",
    description: `LIGHT CONVERSION is a globally renowned ultrafast laser manufacturer, designing and manufacturing femtosecond lasers, wavelength-tunable sources (OPAs), optical parametric chirped-pulse amplifiers (OPCPAs), microscopy sources, and spectroscopy systems. This comprehensive portfolio represents a best-in-class collection of devices tailored for femtosecond applications in industry, medicine, and research.`,
    data: [
    "OPA_Calibration_Protocols",
    "OPCPA_Project_Orion",
    "pricelist",
    "PulseStability_2019",
    "Optics_Supply_Master",
    "ISO_Certification",
    "laser_diagrams",
    "RD_Notes_LabA",
    "Beamline_Setup_v2",
    "Customer_Install_Data",
    "MaterialDispersion",
    "NonlinearCrystals",
    "CoatingSpecs",
    "notebook",
    "Experiment_Setup_03",
    "PhaseMatching_Data",
    "PumpLaser_Characterization",
    "QC_Reports",
    "OPA_Repair_Logs",
    "Customer_Install_Data",
    "EU_Sales_2021",
    "NA_Market_Analysis",
    "MedicalSystem_Specs",
    "Microscopy_DevNotes",
    "Spectroscopy_Config",
    "Firmware_UpdatePack",
    "ControlSoftware_Internal",
    "Support_Tickets_Export",
    "LaserPerformance_Archive",
    "Manufacturing_Schedule_Q3",
    "Supplier_Contracts",
    "MechanicalDrawings_SetB",
    "CAD_Exports_Assembly1",
    "Procurement_Plan",
    "Safety_Audit_Reports",
    "Lab_Compliance_Check",
    "Project_NOVA_Logs",
    "SimulationResults_v5",
    "OpticalFiber_Data",
    "EmployeeDirectory_Internal",
    "FinanceForecast_2021",
    "BoardMinutes_Jan",
    "Innovation_Roadmap",
    "ProtoUnit_Testing",
    "FieldService_Activity",
    "Archive_1618",
    "lasertuning_Guide",
    "Confidential_IP"
    ]
  },

};
